### ISSUE TITLE
Missing alignment file for running notebook

### ISSUE THREAD

**Issue by krdav** [samsinai/VAE_protein_function#1]
I would like to run the example from your notebook but am missing the HMM alignment file: `PABP_YEAST_hmmerbit_plmc_n5_m30_f50_t0.2_r115-210_id100_b48.a2m`

Any ways of getting this?

Btw. great work on the notebook/blog and arXiv article!

**Comment by samsinai** [comment]
Thanks, I have added the alignment file here. You can access more of them from Mark's lab link provided in the readme.

**Comment by krdav** [comment]
Sweet, thanks!
